In [1]:
import pandas as pd

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.width', None)

In [3]:
cabecera = ['NUMENCRIPTADO','TPO_DOCTO','ADU','FORM','FECVENCI','CODCOMUN','NUM_UNICO_IMPORTADOR','CODPAISCON','DESDIRALM','CODCOMRS','ADUCTROL','NUMPLAZO','INDPARCIAL','NUMHOJINS','TOTINSUM','CODALMA','NUM_RS','FEC_RS','ADUA_RS','NUMHOJANE','NUM_SEC','PA_ORIG','PA_ADQ','VIA_TRAN','TRANSB','PTO_EMB','PTO_DESEM','TPO_CARGA','ALMACEN','FEC_ALMAC','FECRETIRO','NU_REGR','ANO_REG','CODVISBUEN','NUMREGLA','NUMANORES','CODULTVB','PAGO_GRAV','FECTRA','FECACEP','GNOM_CIA_T','CODPAISCIA','NUMRUTCIA','DIGVERCIA','NUM_MANIF','NUM_MANIF1','NUM_MANIF2','FEC_MANIF','NUM_CONOC','FEC_CONOC','NOMEMISOR','NUMRUTEMI','DIGVEREMI','GREG_IMP','REG_IMP','BCO_COM','CODORDIV','FORM_PAGO','NUMDIAS','VALEXFAB','MONEDA','MONGASFOB','CL_COMPRA','TOT_ITEMS','FOB','TOT_HOJAS','COD_FLE','FLETE','TOT_BULTOS','COD_SEG','SEGURO','TOT_PESO','CIF','NUM_AUT','FEC_AUT','GBCOCEN','ID_BULTOS','TPO_BUL1','CANT_BUL1','TPO_BUL2','CANT_BUL2','TPO_BUL3','CANT_BUL3','TPO_BUL4','CANT_BUL4','TPO_BUL5','CANT_BUL5','TPO_BUL6','CANT_BUL6','TPO_BUL7','CANT_BUL7','TPO_BUL8','CANT_BUL8','CTA_OTRO','MON_OTRO','CTA_OTR1','MON_OTR1','CTA_OTR2','MON_OTR2','CTA_OTR3','MON_OTR3','CTA_OTR4','MON_OTR4','CTA_OTR5','MON_OTR5','CTA_OTR6','MON_OTR6','CTA_OTR7','MON_OTR7','MON_178','MON_191','FEC_501','VAL_601','FEC_502','VAL_602','FEC_503','VAL_603','FEC_504','VAL_604','FEC_505','VAL_605','FEC_506','VAL_606','FEC_507','VAL_607','TASA','NCUOTAS','ADU_DI','NUM_DI','FEC_DI','MON_699','MON_199','NUMITEM','DNOMBRE','DMARCA','DVARIEDAD','DOTRO1','DOTRO2','ATR_5','ATR_6','SAJU_ITEM','AJU_ITEM','CANT_MERC','MERMAS','MEDIDA','PRE_UNIT','ARANC_ALA','NUMCOR','NUMACU','CODOBS1','DESOBS1','CODOBS2','DESOBS2','CODOBS3','DESOBS3','CODOBS4','DESOBS4','ARANC_NAC','CIF_ITEM','ADVAL_ALA','ADVAL','VALAD','OTRO1','CTA1','SIGVAL1','VAL1','OTRO2','CTA2','SIGVAL2','VAL2','OTRO3','CTA3','SIGVAL3','VAL3','OTRO4','CTA4','SIGVAL4','VAL4']

In [4]:
df = pd.read_csv("https://deinsoluciones.cl/web_semantica/importaciones_enero_2024.csv", delimiter=";",encoding='utf-8', header=None)
df.columns = cabecera

<ipython-input-4-b6dfb4604874>:1: DtypeWarning: Columns (43,44,45,46,98,100,107,108,139,149,151,153,155,159,162,166,170,172,173,176,177) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("https://deinsoluciones.cl/web_semantica/importaciones_enero_2024.csv", delimiter=";",encoding='utf-8', header=None)

In [5]:
df.head()

,NUMENCRIPTADO,TPO_DOCTO,ADU,FORM,FECVENCI,CODCOMUN,NUM_UNICO_IMPORTADOR,CODPAISCON,DESDIRALM,CODCOMRS,ADUCTROL,NUMPLAZO,INDPARCIAL,NUMHOJINS,TOTINSUM,CODALMA,NUM_RS,FEC_RS,ADUA_RS,NUMHOJANE,NUM_SEC,PA_ORIG,PA_ADQ,VIA_TRAN,TRANSB,PTO_EMB,PTO_DESEM,TPO_CARGA,ALMACEN,FEC_ALMAC,FECRETIRO,NU_REGR,ANO_REG,CODVISBUEN,NUMREGLA,NUMANORES,CODULTVB,PAGO_GRAV,FECTRA,FECACEP,GNOM_CIA_T,CODPAISCIA,NUMRUTCIA,DIGVERCIA,NUM_MANIF,NUM_MANIF1,NUM_MANIF2,FEC_MANIF,NUM_CONOC,FEC_CONOC,NOMEMISOR,NUMRUTEMI,DIGVEREMI,GREG_IMP,REG_IMP,BCO_COM,CODORDIV,FORM_PAGO,NUMDIAS,VALEXFAB,MONEDA,MONGASFOB,CL_COMPRA,TOT_ITEMS,FOB,TOT_HOJAS,COD_FLE,FLETE,TOT_BULTOS,COD_SEG,SEGURO,TOT_PESO,CIF,NUM_AUT,FEC_AUT,GBCOCEN,ID_BULTOS,TPO_BUL1,CANT_BUL1,TPO_BUL2,CANT_BUL2,TPO_BUL3,CANT_BUL3,TPO_BUL4,CANT_BUL4,TPO_BUL5,CANT_BUL5,TPO_BUL6,CANT_BUL6,TPO_BUL7,CANT_BUL7,TPO_BUL8,CANT_BUL8,CTA_OTRO,MON_OTRO,CTA_OTR1,MON_OTR1,CTA_OTR2,MON_OTR2,CTA_OTR3,MON_OTR3,CTA_OTR4,MON_OTR4,CTA_OTR5,MON_OTR5,CTA_OTR6,MON_OTR6,CTA_OTR7,MON_OTR7,MON_178,MON_191,FEC_501,VAL_601,FEC_502,VAL_602,FEC_503,VAL_603,FEC_504,VAL_604,FEC_505,VAL_605,FEC_506,VAL_606,FEC_507,VAL_607,TASA,NCUOTAS,ADU_DI,NUM_DI,FEC_DI,MON_699,MON_199,NUMITEM,DNOMBRE,DMARCA,DVARIEDAD,DOTRO1,DOTRO2,ATR_5,ATR_6,SAJU_ITEM,AJU_ITEM,CANT_MERC,MERMAS,MEDIDA,PRE_UNIT,ARANC_ALA,NUMCOR,NUMACU,CODOBS1,DESOBS1,CODOBS2,DESOBS2,CODOBS3,DESOBS3,CODOBS4,DESOBS4,ARANC_NAC,CIF_ITEM,ADVAL_ALA,ADVAL,VALAD,OTRO1,CTA1,SIGVAL1,VAL1,OTRO2,CTA2,SIGVAL2,VAL2,OTRO3,CTA3,SIGVAL3,VAL3,OTRO4,CTA4,SIGVAL4,VAL4
0,20970586,151,39,15,18012024,13124,12816,563,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,336,563,1,NaN,592,906,R,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,1,3012024,3012024,HAPAG LLOYD,997,76049840,8,239108,NaN,NaN,0,LCUHAM2311BCZM9(H)SEAEXPJ32409,8122023,SEAFAIR CHILE SPA,77554368,K,GENERAL,1,0,0,32,0,0,142,0,2,3,"37682,71",2,0,"546,57",3,7,"83,44",2672,"38312,72",999,0,,,74.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,223.0,"2298,76",NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,"7716,18","10014,94",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,0,1,SIN-CODIGO ~GRAPA ROSETA,WILHELM-F,22MM,MATERIAL DE ANDAMIAJE,NaN,NaN,NaN,NaN,0,1212,0,6,"23,872772",0.0,0,NaN,76,SE SOLIC.REGIMEN PREF.,99,00001200.000000 UNIDADES,NaN,NaN,NaN,NaN,73084000,"29417,54",6,223.0,"1765,05",19,178.0,+,"5924,69",0,NaN,NaN,0,0,NaN,NaN,0,0,NaN,NaN,0
1,20970586,151,39,15,18012024,13124,12816,563,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,336,563,1,NaN,592,906,R,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,1,3012024,3012024,HAPAG LLOYD,997,76049840,8,239108,NaN,NaN,0,LCUHAM2311BCZM9(H)SEAEXPJ32409,8122023,SEAFAIR CHILE SPA,77554368,K,GENERAL,1,0,0,32,0,0,142,0,2,3,"37682,71",2,0,"546,57",3,7,"83,44",2672,"38312,72",999,0,,,74.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,223.0,"2298,76",NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,"7716,18","10014,94",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,0,2,SIN-CODIGO ~GRAPA,WILHELM-F,GIRATORIA,MATERIAL DE ANDAMIAJE,NaN,NaN,NaN,NaN,0,1350,0,6,"5,839904",0.0,0,NaN,76,SE SOLIC.REGIMEN PREF.,99,00000900.000000 UNIDADES,NaN,NaN,NaN,NaN,73084000,"8015,68",6,223.0,"480,94",19,178.0,+,"1614,36",0,NaN,NaN,0,0,NaN,NaN,0,0,NaN,NaN,0
2,20970586,151,39,15,18012024,13124,12816,563,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,336,563,1,NaN,592,906,R,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,1,3012024,3012024,HAPAG LLOYD,997,76049840,8,239108,NaN,NaN,0,LCUHAM2311BCZM9(H)SEAEXPJ32409,8122023,SEAFAIR CHILE SPA,77554368,K,GENERAL,1,0,0,32,0,0,142,0,2,3,"37682,71",2,0,"546,57",3,7,"83,44",2672,"38312,72",999,0,,,74.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,223.0,"2298,76",NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,"7716,18","10014,94",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,0,3,SIN-CODIGO ~PASADOR,WILHELM-F,DE SEGURIDAD,LAS DEMAS MANUFACTURAS DE ACER,O,NaN,NaN,NaN,0,110,0,6,"7,864",0.0,0,NaN,99,00000800.000000 UNIDADES,21,MERC.DE MAS DE UN NOMBRE Y MOD,98.0,MERCANCIA AGRUPADA,NaN,NaN,73262000,"879,5",6,223.0,"52,77",19,178.0,+,"177,13",0,NaN,NaN,0,0,NaN,NaN,0,0,NaN,NaN,0
3,20982944,151,39,15,26012024,13101,9999,336,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,336,336,1,NaN,413,906,R,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,4,11012024,11012024,OCEAN NETWORK EXPRES,997,76788001,4,238735,NaN,NaN,0,ONEYNB3JJA086700,30112023,OCEAN NETWORK EXPRESS PTE.LTD,76788001,4,TLC-CHCHI,96,0,0,32,0,0,13,0,5,6,"15363,58",2,0,1265,1,2,"307,27","3887,4","16935,85",999,0,,,74.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,223.0,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,"3217,83","3217,83",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,0,1,SIN-CODIGO ~FRONTAL LATA,CHANGZHOU-F,I.I GAHG SOHC-12 VALV 4X2,PARTES DE RADIADORES,NaN,NaN,NaN,NaN,0,"100,5",0,6,"2,406965",87089100.0,0,816.0,99,00000020.000000 UNIDADES,20,MERCANCIAS DE MAS DE UN MODELO,NaN,NaN,NaN,NaN,87089100,"266,66",0,223.0,0,19,178.0,+,"50,67",0,NaN,NaN,0,0,NaN,NaN,0,0,NaN,NaN,0
4,20982944,151,39,15,26012024,13101,9999,336,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,336,336,1,NaN,413,906,R,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,4,11012024,11012024,OCEAN NETWORK EXPRES,997,76788001,4,238735,NaN,NaN,0,ONEYNB3JJA086700,30112023,OCEAN NETWORK EXPRESS PTE.LTD,76788001,4,TLC-CHCHI,96,0,0,32,0,0,13,0,5,6,"15363,58",2,0,1265,1,2,"307,27","3887,4","16935,85",999,0,,,74.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,223.0,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,"3217,83","3217,83",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,0,2,SIN-CODIGO ~ESPEJO RETROVISOR,CHANGZHOU-F,ACCENT 1.4 G4FA DOHC 16 VALV 4,X2PARA VEHICULOS AUTOMOVILES,NaN,NaN,NaN,NaN,0,19,0,6,"5,894737",70091000.0,0,816.0,99,00000020.000000 UNIDADES,20,MERCANCIAS DE MAS DE UN MODELO,NaN,NaN,NaN,NaN,70091000,"123,46",0,223.0,0,19,178.0,+,"23,46",0,NaN,NaN,0,0,NaN,NaN,0,0,NaN,NaN,0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 340884 entries, 0 to 340883
Columns: 178 entries, NUMENCRIPTADO to VAL4
dtypes: float64(39), int64(77), object(62)
memory usage: 462.9+ MB

In [7]:
import json
import requests

# URL del archivo JSON
json_file_url = 'https://deinsoluciones.cl/web_semantica/datos_importaciones.json'

# Descargar el JSON desde la URL
response = requests.get(json_file_url)

# Verificar si la solicitud fue exitosa
if response.status_code == 200:
    data = response.json()  # Convertir la respuesta a JSON

    # Convertir cada sección del JSON en un DataFrame
    df_aduanas = pd.DataFrame(data['aduanas'])
    df_monedas = pd.DataFrame(data['monedas'])
    df_paises = pd.DataFrame(data['paises'])
    df_puertos = pd.DataFrame(data['puertos'])
    df_vias_transporte = pd.DataFrame(data['vias_transporte'])
    df_tipo_carga = pd.DataFrame(data['tipo_carga'])
    df_comunas = pd.DataFrame(data['comunas'])

    # Renombrar columnas
    df_aduanas.columns = ['cod_aduana','nombre_aduana']
    df_monedas.columns = ['cod_moneda','nombre_moneda']
    df_paises.columns = ['cod_pais','nombre_pais']
    df_puertos.columns = ['cod_puerto','nombre_puerto']
    df_vias_transporte.columns = ['cod_via_transporte','nombre_via_transporte']
    df_tipo_carga.columns = ['cod_tipo_carga','nombre_tipo_carga']
    df_comunas.columns = ['cod_comuna','nombre_comuna']

else:
    print(f"Error al obtener el archivo JSON. Código de estado: {response.status_code}")

In [8]:
# Ruta del archivo en Colab (asegúrate de subirlo primero)
json_m_file_path = 'https://deinsoluciones.cl/web_semantica/manifiestos_maritimos.json'

# Descargar el JSON desde la URL
response = requests.get(json_m_file_path)

# Verificar si la solicitud fue exitosa
if response.status_code == 200:
    data = response.json()  # Convertir la respuesta a JSON
    print(type(data))  # Verifica si es una lista o un diccionario
    #print(data[:2])  # Muestra los primeros elementos para analizar la estructura
    df_manifiestos_maritimos = None
    # Convertir directamente la lista en un DataFrame
    df_manifiestos_maritimos = pd.DataFrame(data['manifiestos_maritimos'])

else:
    print(f"Error al obtener el archivo JSON. Código de estado: {response.status_code}")

df_manifiestos_maritimos.head()

<class 'dict'>

,Número_Prog,Puerto,Nombre_Nave,Número_Viaje,Nombre_Agente_Naves,Fecha_Arribo_Zarpe,Fecha_Registro,Fecha_Efectiva_Arribo_Zarpe,Registro_Efectivo,Tipo,Estado
0,236691,SAN ANTONIO,NORWEGIAN SUN,01/2024,A. J. BROOM Y CIA. SAC,22/01/2024,29/10/2023 16:29:52,22/01/2024 08:45,22/01/2024 10:23:59,INGRESO,MODIFICADO
1,237281,SAN ANTONIO,AZAMARA QUEST,01/2024,A. J. BROOM Y CIA. SAC,22/01/2024,10/11/2023 13:59:59,22/01/2024 07:30,22/01/2024 09:55:00,INGRESO,MODIFICADO
2,238013,SAN ANTONIO,NEW LEADER,4,AGENCIAS MARITIMAS AGENTAL LIMITADA,13/12/2023,30/11/2023 09:50:53,03/01/2024 06:50,03/01/2024 07:33:33,INGRESO,MODIFICADO
3,238226,SAN ANTONIO,H CYGNUS,021,AGENCIAS UNIVERSALES S.A.,11/01/2024,06/12/2023 09:55:58,,,INGRESO,ANULADO
4,238244,SAN ANTONIO,TONGALA,0149,AGENCIAS UNIVERSALES S.A.,02/01/2024,06/12/2023 12:12:44,01/01/2024 22:22,01/01/2024 22:58:15,INGRESO,MODIFICADO

In [9]:
!pip install rdflib

Requirement already satisfied: rdflib in /usr/local/lib/python3.11/dist-packages (7.1.3)
Requirement already satisfied: pyparsing<4,>=2.1.0 in /usr/local/lib/python3.11/dist-packages (from rdflib) (3.2.1)

In [10]:
from rdflib import Graph, Namespace, Literal, RDF
import os


# URL del archivo JSON
json_url = "https://deinsoluciones.cl/web_semantica/datos_importaciones.json"

# Descargar el JSON desde la URL
response = requests.get(json_url)

# Verificar si la solicitud fue exitosa
if response.status_code == 200:
    data = response.json()  # Convertir la respuesta a JSON
else:
    print(f"Error al obtener el archivo JSON. Código de estado: {response.status_code}")
    exit()

# Lista de categorías y su versión singular para asignar los prefijos correctos
categorias = ['aduanas', 'paises', 'puertos']
singular = ['aduana', 'pais', 'puerto']

# Definir namespaces con prefijo vacío para "http://example.org/"
default_ns = Namespace("http://example.org/")
xsd = Namespace("http://www.w3.org/2001/XMLSchema#")
schema = Namespace("http://schema.org/")

# Prefijos deseados para el archivo final
desired_prefixes = """\
prefix :       <http://example.org/>
prefix xsd:    <http://www.w3.org/2001/XMLSchema#>
prefix rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix schema: <http://schema.org/>
"""

# Procesar cada categoría
for i, categoria in enumerate(categorias):
    if categoria in data:
        # Extraer la información de la categoría actual
        registros = data[categoria]

        # Convertir la información a un DataFrame
        df_registros = pd.DataFrame(registros)

        # Crear un grafo RDF
        g = Graph()
        g.bind("", default_ns)  # Prefijo vacío
        g.bind("xsd", xsd)
        g.bind("schema", schema)

        # Obtener el nombre en singular correspondiente a la categoría
        singular_categoria = singular[i]

        # Agregar datos al grafo RDF utilizando el valor del campo 'Código'
        for _, row in df_registros.iterrows():
            item_id = f"{singular_categoria}{row['Código']}"  # Usar código del JSON
            item_uri = default_ns[item_id]

            g.add((item_uri, RDF.type, default_ns[singular_categoria.capitalize()]))  # Usa la versión singular capitalizada
            g.add((item_uri, schema.nombre, Literal(row['Glosa'], datatype=xsd.string)))

        # Guardar el grafo en formato RDF temporal
        temp_file = f"{categoria}_temp.ttl"
        g.serialize(destination=temp_file, format="turtle")

        # Leer el archivo generado y modificar su contenido
        with open(temp_file, 'r', encoding='utf-8') as file:
            lines = file.readlines()

        # Procesar líneas para realizar las modificaciones
        processed_lines = []
        for line in lines:
            if not line.startswith("@prefix"):  # Eliminar prefijos generados automáticamente
                line = line.replace(" a ", " rdf:type ")  # Reemplazar ' a ' por ' rdf:type '
                line = line.replace("schema1:", "schema:")  # Corregir prefijo schema
                processed_lines.append(line)

        # Guardar el resultado final con los cambios
        output_file = f"{categoria}.ttl"
        with open(output_file, 'w', encoding='utf-8') as file:
            file.write(desired_prefixes + "\n")
            file.writelines(processed_lines)

        # Eliminar el archivo temporal
        os.remove(temp_file)

        print(f"✅ Archivo RDF generado con éxito: '{output_file}'")
    else:
        print(f"⚠️ Advertencia: La categoría '{categoria}' no está presente en el JSON.")

✅ Archivo RDF generado con éxito: 'aduanas.ttl'
✅ Archivo RDF generado con éxito: 'paises.ttl'
✅ Archivo RDF generado con éxito: 'puertos.ttl'

In [11]:
df_filtrado = None
df_filtrado = df.query("VIA_TRAN == 1")

In [12]:
df_filtrado['ARANC_NAC'] = df_filtrado['ARANC_NAC'].astype(str)
df_filtrado_1 = df_filtrado.query("ARANC_NAC.str.startswith('8702', na=False)")
df_filtrado_2 = df_filtrado.query("ARANC_NAC.str.startswith('8703', na=False)")
df_filtrado_3 = df_filtrado.query("ARANC_NAC.str.startswith('8704', na=False)")
df_filtrado_4 = df_filtrado.query("ARANC_NAC.str.startswith('8705', na=False)")
df_importaciones = None
df_importaciones = pd.concat([df_filtrado_1, df_filtrado_2, df_filtrado_3, df_filtrado_4], ignore_index=True)

<ipython-input-12-3175ca4b178a>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtrado['ARANC_NAC'] = df_filtrado['ARANC_NAC'].astype(str)

In [13]:
df_resumido = None
df_resumido = df_importaciones[['NUMENCRIPTADO','TPO_DOCTO','TOT_ITEMS','ADU','CODCOMUN','NUM_UNICO_IMPORTADOR','PA_ORIG','PA_ADQ','VIA_TRAN','PTO_EMB','PTO_DESEM','TPO_CARGA','NUM_MANIF','NUM_CONOC','FEC_CONOC','NOMEMISOR','MONEDA','FOB','FLETE','SEGURO','CIF','NUMITEM', 'CANT_MERC','ARANC_NAC','DNOMBRE','DMARCA','DVARIEDAD','DOTRO1','DOTRO2','ATR_5','ATR_6']]

In [14]:
df_resumido['NUM_MANIF'] = df_resumido['NUM_MANIF'].astype(str)
df_manifiestos_maritimos['Número_Prog'] = df_manifiestos_maritimos['Número_Prog'].astype(str)

<ipython-input-14-6504fcb646cb>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_resumido['NUM_MANIF'] = df_resumido['NUM_MANIF'].astype(str)

In [15]:
# Reemplazar ".0" por vacío en la columna NUM_MANIF
df_resumido['NUM_MANIF'] = df_resumido['NUM_MANIF'].astype(str).str.replace(r'\.0$', '', regex=True)

<ipython-input-15-67b2a998ad2e>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_resumido['NUM_MANIF'] = df_resumido['NUM_MANIF'].astype(str).str.replace(r'\.0$', '', regex=True)

In [16]:
# Realizar los cruces de datos
df_resumido = df_resumido.merge(df_aduanas, left_on='ADU', right_on='cod_aduana', how='left', suffixes=('', '_aduana'))
df_resumido = df_resumido.merge(df_comunas, left_on='CODCOMUN', right_on='cod_comuna', how='left', suffixes=('', '_comuna'))
df_resumido = df_resumido.merge(df_monedas, left_on='MONEDA', right_on='cod_moneda', how='left', suffixes=('', '_moneda'))
df_resumido = df_resumido.merge(df_paises, left_on='PA_ORIG', right_on='cod_pais', how='left', suffixes=('', '_pais_origen'))
df_resumido = df_resumido.merge(df_paises, left_on='PA_ADQ', right_on='cod_pais', how='left', suffixes=('', '_pais_adq'))
df_resumido = df_resumido.merge(df_puertos, left_on='PTO_EMB', right_on='cod_puerto', how='left', suffixes=('', '_pto_emb'))
df_resumido = df_resumido.merge(df_puertos, left_on='PTO_DESEM', right_on='cod_puerto', how='left', suffixes=('', '_pto_desem'))
df_resumido = df_resumido.merge(df_vias_transporte, left_on='VIA_TRAN', right_on='cod_via_transporte', how='left', suffixes=('', '_via'))
df_resumido = df_resumido.merge(df_tipo_carga, left_on='TPO_CARGA', right_on='cod_tipo_carga', how='left', suffixes=('', '_carga'))
df_resumido = df_resumido.merge(df_manifiestos_maritimos, left_on='NUM_MANIF', right_on='Número_Prog', how='left', suffixes=('', '_mfto'))
df_resumido.head()

,NUMENCRIPTADO,TPO_DOCTO,TOT_ITEMS,ADU,CODCOMUN,NUM_UNICO_IMPORTADOR,PA_ORIG,PA_ADQ,VIA_TRAN,PTO_EMB,PTO_DESEM,TPO_CARGA,NUM_MANIF,NUM_CONOC,FEC_CONOC,NOMEMISOR,MONEDA,FOB,FLETE,SEGURO,CIF,NUMITEM,CANT_MERC,ARANC_NAC,DNOMBRE,DMARCA,DVARIEDAD,DOTRO1,DOTRO2,ATR_5,ATR_6,cod_aduana,nombre_aduana,cod_comuna,nombre_comuna,cod_moneda,nombre_moneda,cod_pais,nombre_pais,cod_pais_pais_adq,nombre_pais_pais_adq,cod_puerto,nombre_puerto,cod_puerto_pto_desem,nombre_puerto_pto_desem,cod_via_transporte,nombre_via_transporte,cod_tipo_carga,nombre_tipo_carga,Número_Prog,Puerto,Nombre_Nave,Número_Viaje,Nombre_Agente_Naves,Fecha_Arribo_Zarpe,Fecha_Registro,Fecha_Efectiva_Arribo_Zarpe,Registro_Efectivo,Tipo,Estado
0,20955958,151,1,39,13302,12516,336,336,1,413,906,R,239233,(M)COSU6370424530,3122023,MARITRANS,13,309000,25035,340,334375,1,4,87024090,XML6700E ~BUS ELE,GOLDEN DRAGON,XML6700E,"POTENCIA 155 KW., CAPACIDAD DE","PASAJEROS 21 SENTADOS, CAPAC.","DE CARGA UTIL 4.500 KG., PBV","6400 KG., PARA TRANSPORTE DEPE",39,SAN ANTONIO,13302,LAMPA,13,DOLAR USA,336,CHINA,336,CHINA,413,OTROS PTOS.DE CHINA,906,SAN ANTONIO,1,"MARITIMA, FLUVIAL Y LACUSTRE",R,GENERAL,239233,SAN ANTONIO,XIN YA ZHOU,160E,SOCIEDAD MARITIMA Y COMERCIAL SOMARCO LTDA.,13/01/2024,03/01/2024 10:56:20,14/01/2024 08:45,14/01/2024 09:48:01,INGRESO,MODIFICADO
1,20981434,103,1,39,13124,10870,333,333,1,423,906,R,237767,EUKOHUSQ1935013,31102023,EUKOR CAR CARRIERS,13,22437,"1610,02","18,23","24065,25",1,1,87021019,SZBB2FC57SS409-4~MINIBUS~ D,HYUNDAI,STARIA 2024,A11 CC2200 PBV 3190 KB,NaN,NaN,NaN,39,SAN ANTONIO,13124,PUDAHUEL,13,DOLAR USA,333,COREA DEL SUR,333,COREA DEL SUR,423,OTROS PTOS. COREA S,906,SAN ANTONIO,1,"MARITIMA, FLUVIAL Y LACUSTRE",R,GENERAL,237767,SAN ANTONIO,BESS,045,IAN TAYLOR Y CIA. S.A.,08/12/2023,23/11/2023 14:28:52,08/12/2023 08:40,08/12/2023 09:05:36,INGRESO,MODIFICADO
2,21014856,103,1,39,13124,10870,333,333,1,423,906,R,237767,EUKOHUSQ1935017,31102023,EUKOR CAR CARRIERS,13,22437,"1610,02","18,21","24065,23",1,1,87021019,SZBB2FC57SS409-4~MINIBUS~ D,HYUNDAI,STARIA 2024,A11 CC2200 PBV 3190 KB,NaN,NaN,NaN,39,SAN ANTONIO,13124,PUDAHUEL,13,DOLAR USA,333,COREA DEL SUR,333,COREA DEL SUR,423,OTROS PTOS. COREA S,906,SAN ANTONIO,1,"MARITIMA, FLUVIAL Y LACUSTRE",R,GENERAL,237767,SAN ANTONIO,BESS,045,IAN TAYLOR Y CIA. S.A.,08/12/2023,23/11/2023 14:28:52,08/12/2023 08:40,08/12/2023 09:05:36,INGRESO,MODIFICADO
3,20985879,103,1,39,13124,10870,333,333,1,423,906,R,238749,HDGLKRCL0562033,30112023,HYUNDAI GLOVIS,13,22437,"1630,32","18,24","24085,56",1,1,87021019,SZBB2FC57SS409-4~MINIBUS~ D,HYUNDAI,STARIA 2024,A11 CC2200 PBV 3190 KB,NaN,NaN,NaN,39,SAN ANTONIO,13124,PUDAHUEL,13,DOLAR USA,333,COREA DEL SUR,333,COREA DEL SUR,423,OTROS PTOS. COREA S,906,SAN ANTONIO,1,"MARITIMA, FLUVIAL Y LACUSTRE",R,GENERAL,238749,SAN ANTONIO,MORNING CHORUS,155,IAN TAYLOR Y CIA. S.A.,01/01/2024,19/12/2023 16:00:29,01/01/2024 13:40,01/01/2024 14:17:38,INGRESO,MODIFICADO
4,20993803,151,2,39,13124,10870,333,333,1,423,906,R,239633,EUKOHUSQ1944340,28122023,EUKOR CAR CARRIERS,13,292031,"21194,16","237,45","313462,61",1,8,87021019,SZBB2FC57SS409-4~MINIBUS~ D,HYUNDAI,STARIA 2024,A11 CC2200 PBV 3190 KB,NaN,NaN,NaN,39,SAN ANTONIO,13124,PUDAHUEL,13,DOLAR USA,333,COREA DEL SUR,333,COREA DEL SUR,423,OTROS PTOS. COREA S,906,SAN ANTONIO,1,"MARITIMA, FLUVIAL Y LACUSTRE",R,GENERAL,239633,SAN ANTONIO,MORNING CHERRY,089,IAN TAYLOR Y CIA. S.A.,01/02/2024,12/01/2024 14:31:24,04/02/2024 03:30,04/02/2024 04:04:59,INGRESO,MODIFICADO

In [17]:
df_resumido = df_resumido.rename(columns={
    "nombre_aduana": "NOMBRE_ADUANA",
    "nombre_comuna": "NOMBRE_COMUNA",
    "nombre_pais": "NOMBRE_PAIS_ORIG",
    "nombre_pais_pais_adq": "NOMBRE_PAIS_ADQ",
    "nombre_via_transporte": "NOMBRE_VIA_TRANSPORTE",
    "nombre_puerto": "NOMBRE_PUERTO_EMBARQUE",
    "nombre_puerto_pto_desem": "NOMBRE_PUERTO_DESEMBARQUE",
    "nombre_tipo_carga": "NOMBRE_TIPO_CARGA",
    "Nombre_Nave": "NOMBRE_NAVE",
    "Nombre_Agente_Naves": "NOMBRE_AGENTE_DE_NAVES",
    "nombre_moneda": "NOMBRE_MONEDA"
})

In [18]:
df_resumido.head()

,NUMENCRIPTADO,TPO_DOCTO,TOT_ITEMS,ADU,CODCOMUN,NUM_UNICO_IMPORTADOR,PA_ORIG,PA_ADQ,VIA_TRAN,PTO_EMB,PTO_DESEM,TPO_CARGA,NUM_MANIF,NUM_CONOC,FEC_CONOC,NOMEMISOR,MONEDA,FOB,FLETE,SEGURO,CIF,NUMITEM,CANT_MERC,ARANC_NAC,DNOMBRE,DMARCA,DVARIEDAD,DOTRO1,DOTRO2,ATR_5,ATR_6,cod_aduana,NOMBRE_ADUANA,cod_comuna,NOMBRE_COMUNA,cod_moneda,NOMBRE_MONEDA,cod_pais,NOMBRE_PAIS_ORIG,cod_pais_pais_adq,NOMBRE_PAIS_ADQ,cod_puerto,NOMBRE_PUERTO_EMBARQUE,cod_puerto_pto_desem,NOMBRE_PUERTO_DESEMBARQUE,cod_via_transporte,NOMBRE_VIA_TRANSPORTE,cod_tipo_carga,NOMBRE_TIPO_CARGA,Número_Prog,Puerto,NOMBRE_NAVE,Número_Viaje,NOMBRE_AGENTE_DE_NAVES,Fecha_Arribo_Zarpe,Fecha_Registro,Fecha_Efectiva_Arribo_Zarpe,Registro_Efectivo,Tipo,Estado
0,20955958,151,1,39,13302,12516,336,336,1,413,906,R,239233,(M)COSU6370424530,3122023,MARITRANS,13,309000,25035,340,334375,1,4,87024090,XML6700E ~BUS ELE,GOLDEN DRAGON,XML6700E,"POTENCIA 155 KW., CAPACIDAD DE","PASAJEROS 21 SENTADOS, CAPAC.","DE CARGA UTIL 4.500 KG., PBV","6400 KG., PARA TRANSPORTE DEPE",39,SAN ANTONIO,13302,LAMPA,13,DOLAR USA,336,CHINA,336,CHINA,413,OTROS PTOS.DE CHINA,906,SAN ANTONIO,1,"MARITIMA, FLUVIAL Y LACUSTRE",R,GENERAL,239233,SAN ANTONIO,XIN YA ZHOU,160E,SOCIEDAD MARITIMA Y COMERCIAL SOMARCO LTDA.,13/01/2024,03/01/2024 10:56:20,14/01/2024 08:45,14/01/2024 09:48:01,INGRESO,MODIFICADO
1,20981434,103,1,39,13124,10870,333,333,1,423,906,R,237767,EUKOHUSQ1935013,31102023,EUKOR CAR CARRIERS,13,22437,"1610,02","18,23","24065,25",1,1,87021019,SZBB2FC57SS409-4~MINIBUS~ D,HYUNDAI,STARIA 2024,A11 CC2200 PBV 3190 KB,NaN,NaN,NaN,39,SAN ANTONIO,13124,PUDAHUEL,13,DOLAR USA,333,COREA DEL SUR,333,COREA DEL SUR,423,OTROS PTOS. COREA S,906,SAN ANTONIO,1,"MARITIMA, FLUVIAL Y LACUSTRE",R,GENERAL,237767,SAN ANTONIO,BESS,045,IAN TAYLOR Y CIA. S.A.,08/12/2023,23/11/2023 14:28:52,08/12/2023 08:40,08/12/2023 09:05:36,INGRESO,MODIFICADO
2,21014856,103,1,39,13124,10870,333,333,1,423,906,R,237767,EUKOHUSQ1935017,31102023,EUKOR CAR CARRIERS,13,22437,"1610,02","18,21","24065,23",1,1,87021019,SZBB2FC57SS409-4~MINIBUS~ D,HYUNDAI,STARIA 2024,A11 CC2200 PBV 3190 KB,NaN,NaN,NaN,39,SAN ANTONIO,13124,PUDAHUEL,13,DOLAR USA,333,COREA DEL SUR,333,COREA DEL SUR,423,OTROS PTOS. COREA S,906,SAN ANTONIO,1,"MARITIMA, FLUVIAL Y LACUSTRE",R,GENERAL,237767,SAN ANTONIO,BESS,045,IAN TAYLOR Y CIA. S.A.,08/12/2023,23/11/2023 14:28:52,08/12/2023 08:40,08/12/2023 09:05:36,INGRESO,MODIFICADO
3,20985879,103,1,39,13124,10870,333,333,1,423,906,R,238749,HDGLKRCL0562033,30112023,HYUNDAI GLOVIS,13,22437,"1630,32","18,24","24085,56",1,1,87021019,SZBB2FC57SS409-4~MINIBUS~ D,HYUNDAI,STARIA 2024,A11 CC2200 PBV 3190 KB,NaN,NaN,NaN,39,SAN ANTONIO,13124,PUDAHUEL,13,DOLAR USA,333,COREA DEL SUR,333,COREA DEL SUR,423,OTROS PTOS. COREA S,906,SAN ANTONIO,1,"MARITIMA, FLUVIAL Y LACUSTRE",R,GENERAL,238749,SAN ANTONIO,MORNING CHORUS,155,IAN TAYLOR Y CIA. S.A.,01/01/2024,19/12/2023 16:00:29,01/01/2024 13:40,01/01/2024 14:17:38,INGRESO,MODIFICADO
4,20993803,151,2,39,13124,10870,333,333,1,423,906,R,239633,EUKOHUSQ1944340,28122023,EUKOR CAR CARRIERS,13,292031,"21194,16","237,45","313462,61",1,8,87021019,SZBB2FC57SS409-4~MINIBUS~ D,HYUNDAI,STARIA 2024,A11 CC2200 PBV 3190 KB,NaN,NaN,NaN,39,SAN ANTONIO,13124,PUDAHUEL,13,DOLAR USA,333,COREA DEL SUR,333,COREA DEL SUR,423,OTROS PTOS. COREA S,906,SAN ANTONIO,1,"MARITIMA, FLUVIAL Y LACUSTRE",R,GENERAL,239633,SAN ANTONIO,MORNING CHERRY,089,IAN TAYLOR Y CIA. S.A.,01/02/2024,12/01/2024 14:31:24,04/02/2024 03:30,04/02/2024 04:04:59,INGRESO,MODIFICADO

In [19]:
# Eliminar duplicados para obtener combinaciones únicas
df_importadores_unicos = None
df_importadores_unicos = df_resumido[['NUM_UNICO_IMPORTADOR', 'NOMBRE_COMUNA']].drop_duplicates()

In [20]:
# Agregar la columna ID como un índice único
df_importadores_unicos.insert(0, 'ID', range(1, len(df_importadores_unicos) + 1))

In [21]:
len(df_importadores_unicos)

119

In [22]:
df_importadores_unicos.to_csv('df_importadores_unicos.csv', index=False, encoding='utf-8')

In [23]:
from rdflib import Graph, Namespace, Literal, RDF, XSD
import os

# Cargar el archivo CSV
csv_file = "https://deinsoluciones.cl/web_semantica/df_importadores_unicos.csv"  # Reemplaza con la ruta de tu archivo CSV
df = pd.read_csv(csv_file,delimiter=",",encoding='utf-8')

# Crear un grafo RDF
g = Graph()

# Definir namespaces con prefijo vacío para "http://example.org/"
default_ns = Namespace("http://example.org/")
xsd = Namespace("http://www.w3.org/2001/XMLSchema#")
schema = Namespace("http://schema.org/")

# Vincular namespaces
g.bind("", default_ns)
g.bind("xsd", xsd)
g.bind("schema", schema)

# Agregar datos al grafo RDF utilizando el prefijo vacío
for _, row in df.iterrows():
    cliente_id = f"cliente{row['ID']}"
    cliente_uri = default_ns[cliente_id]

    g.add((cliente_uri, RDF.type, default_ns.Importador))
    g.add((cliente_uri, schema.comuna_importador, Literal(row['NOMBRE_COMUNA'], datatype=XSD.string)))
    # Convertir a string explícitamente para que aparezca con comillas
    g.add((cliente_uri, schema.numero_unico_importador, Literal(str(row['NUM_UNICO_IMPORTADOR']), datatype=XSD.integer)))

# Guardar el grafo en formato RDF temporal
temp_file = "importadores_temp.ttl"
g.serialize(destination=temp_file, format="turtle")

# Leer el archivo generado y modificar su contenido para ajustar el formato
with open(temp_file, 'r', encoding='utf-8') as file:
    lines = file.readlines()

# Nueva cabecera con los prefijos correctos
desired_prefixes = """\
prefix :       <http://example.org/>
prefix xsd:    <http://www.w3.org/2001/XMLSchema#>
prefix rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix schema: <http://schema.org/>
"""

# Procesar líneas para eliminar las llaves '{ }' y corregir el prefijo schema1 a schema
processed_lines = []
for line in lines:
    if not line.startswith("@prefix"):  # Eliminar prefijos generados automáticamente
        line = line.replace(" a ", " rdf:type ")  # Reemplazar ' a ' por ' rdf:type '
        line = line.replace("schema1:", "schema:")  # Corregir prefijo schema
        line = line.replace("{", "").replace("}", "")  # Eliminar llaves
        processed_lines.append(line)

# Guardar el resultado final con los cambios
output_file = "importadores.ttl"
with open(output_file, 'w', encoding='utf-8') as file:
    file.write(desired_prefixes + "\n")
    file.writelines(processed_lines)

# Eliminar el archivo temporal
os.remove(temp_file)

print(f"Archivo RDF generado con éxito: '{output_file}'")

Archivo RDF generado con éxito: 'importadores.ttl'

In [24]:
# Eliminar duplicados para obtener combinaciones únicas
df_naves_unicas = None
df_naves_unicas = df_resumido[['NUM_MANIF','NOMBRE_ADUANA','NOMBRE_NAVE','NOMBRE_AGENTE_DE_NAVES']].drop_duplicates()

In [25]:
# Agregar la columna ID como un índice único
df_naves_unicas.insert(0, 'ID', range(1, len(df_naves_unicas) + 1))

In [26]:
len(df_naves_unicas)

113

In [27]:
df_naves_unicas.to_csv('df_naves_unicas.csv', index=False, encoding='utf-8')

In [28]:
from rdflib import Graph, Namespace, Literal, RDF, XSD
import os

# Cargar el archivo CSV
csv_file = "https://deinsoluciones.cl/web_semantica/df_naves_unicas.csv"  # Reemplaza con la ruta de tu archivo CSV
df = pd.read_csv(csv_file,delimiter=",",encoding='utf-8')

# Crear un grafo RDF
g = Graph()

# Definir namespaces con prefijo vacío para "http://example.org/"
default_ns = Namespace("http://example.org/")
xsd = Namespace("http://www.w3.org/2001/XMLSchema#")
schema = Namespace("http://schema.org/")

# Vincular namespaces
g.bind("", default_ns)
g.bind("xsd", xsd)
g.bind("schema", schema)

# Agregar datos al grafo RDF utilizando el prefijo vacío
for _, row in df.iterrows():
    nave_id = f"nave{row['ID']}"
    nave_uri = default_ns[nave_id]

    g.add((nave_uri, RDF.type, default_ns.Nave))
    g.add((nave_uri, schema.manifiesto, Literal(row['NUM_MANIF'], datatype=XSD.string)))
    g.add((nave_uri, schema.nombre, Literal(row['NOMBRE_NAVE'], datatype=XSD.string)))
    # Convertir a string explícitamente para que aparezca con comillas
    g.add((nave_uri, schema.agente_nave, Literal(str(row['NOMBRE_AGENTE_DE_NAVES']), datatype=XSD.string)))

# Guardar el grafo en formato RDF temporal
temp_file = "naves_temp.ttl"
g.serialize(destination=temp_file, format="turtle")

# Leer el archivo generado y modificar su contenido para ajustar el formato
with open(temp_file, 'r', encoding='utf-8') as file:
    lines = file.readlines()

# Nueva cabecera con los prefijos correctos
desired_prefixes = """\
prefix :       <http://example.org/>
prefix xsd:    <http://www.w3.org/2001/XMLSchema#>
prefix rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix schema: <http://schema.org/>
"""

# Procesar líneas para eliminar las llaves '{ }' y corregir el prefijo schema1 a schema
processed_lines = []
for line in lines:
    if not line.startswith("@prefix"):  # Eliminar prefijos generados automáticamente
        line = line.replace(" a ", " rdf:type ")  # Reemplazar ' a ' por ' rdf:type '
        line = line.replace("schema1:", "schema:")  # Corregir prefijo schema
        line = line.replace("{", "").replace("}", "")  # Eliminar llaves
        processed_lines.append(line)

# Guardar el resultado final con los cambios
output_file = "naves.ttl"
with open(output_file, 'w', encoding='utf-8') as file:
    file.write(desired_prefixes + "\n")
    file.writelines(processed_lines)

# Eliminar el archivo temporal
os.remove(temp_file)

print(f"Archivo RDF generado con éxito: '{output_file}'")

Archivo RDF generado con éxito: 'naves.ttl'

In [29]:
df_example = None
df_example = df_resumido[['NUMENCRIPTADO','TPO_DOCTO','NOMBRE_ADUANA','NOMBRE_COMUNA','NUM_UNICO_IMPORTADOR','NOMBRE_PAIS_ORIG','NOMBRE_VIA_TRANSPORTE','NOMBRE_PUERTO_EMBARQUE','NOMBRE_PUERTO_DESEMBARQUE','NOMBRE_TIPO_CARGA','NUM_MANIF','NOMBRE_NAVE','NOMBRE_AGENTE_DE_NAVES','NUM_CONOC','FEC_CONOC','NOMEMISOR','NOMBRE_MONEDA','FOB','FLETE','SEGURO','CIF','ARANC_NAC']]

In [30]:
df_resumido['CANT_MERC'] = df_resumido['CANT_MERC'].astype(int)

In [31]:
df_example = df_example.drop_duplicates()

In [32]:
df_example.head()

,NUMENCRIPTADO,TPO_DOCTO,NOMBRE_ADUANA,NOMBRE_COMUNA,NUM_UNICO_IMPORTADOR,NOMBRE_PAIS_ORIG,NOMBRE_VIA_TRANSPORTE,NOMBRE_PUERTO_EMBARQUE,NOMBRE_PUERTO_DESEMBARQUE,NOMBRE_TIPO_CARGA,NUM_MANIF,NOMBRE_NAVE,NOMBRE_AGENTE_DE_NAVES,NUM_CONOC,FEC_CONOC,NOMEMISOR,NOMBRE_MONEDA,FOB,FLETE,SEGURO,CIF,ARANC_NAC
0,20955958,151,SAN ANTONIO,LAMPA,12516,CHINA,"MARITIMA, FLUVIAL Y LACUSTRE",OTROS PTOS.DE CHINA,SAN ANTONIO,GENERAL,239233,XIN YA ZHOU,SOCIEDAD MARITIMA Y COMERCIAL SOMARCO LTDA.,(M)COSU6370424530,3122023,MARITRANS,DOLAR USA,309000,25035,340,334375,87024090
1,20981434,103,SAN ANTONIO,PUDAHUEL,10870,COREA DEL SUR,"MARITIMA, FLUVIAL Y LACUSTRE",OTROS PTOS. COREA S,SAN ANTONIO,GENERAL,237767,BESS,IAN TAYLOR Y CIA. S.A.,EUKOHUSQ1935013,31102023,EUKOR CAR CARRIERS,DOLAR USA,22437,"1610,02","18,23","24065,25",87021019
2,21014856,103,SAN ANTONIO,PUDAHUEL,10870,COREA DEL SUR,"MARITIMA, FLUVIAL Y LACUSTRE",OTROS PTOS. COREA S,SAN ANTONIO,GENERAL,237767,BESS,IAN TAYLOR Y CIA. S.A.,EUKOHUSQ1935017,31102023,EUKOR CAR CARRIERS,DOLAR USA,22437,"1610,02","18,21","24065,23",87021019
3,20985879,103,SAN ANTONIO,PUDAHUEL,10870,COREA DEL SUR,"MARITIMA, FLUVIAL Y LACUSTRE",OTROS PTOS. COREA S,SAN ANTONIO,GENERAL,238749,MORNING CHORUS,IAN TAYLOR Y CIA. S.A.,HDGLKRCL0562033,30112023,HYUNDAI GLOVIS,DOLAR USA,22437,"1630,32","18,24","24085,56",87021019
4,20993803,151,SAN ANTONIO,PUDAHUEL,10870,COREA DEL SUR,"MARITIMA, FLUVIAL Y LACUSTRE",OTROS PTOS. COREA S,SAN ANTONIO,GENERAL,239633,MORNING CHERRY,IAN TAYLOR Y CIA. S.A.,EUKOHUSQ1944340,28122023,EUKOR CAR CARRIERS,DOLAR USA,292031,"21194,16","237,45","313462,61",87021019

In [33]:
# Crear una función para calcular las métricas por cada NUMENCRIPTADO
def calcular_metricas(numencriptado):
    # Filtrar en df_resumido por el valor actual de NUMENCRIPTADO
    subset = df_resumido[df_resumido['NUMENCRIPTADO'] == numencriptado]

    # Calcular la suma de CANT_MERC y el máximo de NUMITEM
    cant_merc_sum = subset['CANT_MERC'].sum()
    numitem_max = subset['NUMITEM'].max()

    return pd.Series({'CANT_MERC_SUM': cant_merc_sum, 'NUMITEM_MAX': numitem_max})

# Aplicar la función para calcular las métricas en cada NUMENCRIPTADO único de df_example
metricas = df_example['NUMENCRIPTADO'].apply(calcular_metricas)

# Unir las métricas calculadas al DataFrame df_example
df_example = pd.concat([df_example.reset_index(drop=True), metricas.reset_index(drop=True)], axis=1)

In [34]:
df_example.query("NUMENCRIPTADO == 20986046", engine='python')

,NUMENCRIPTADO,TPO_DOCTO,NOMBRE_ADUANA,NOMBRE_COMUNA,NUM_UNICO_IMPORTADOR,NOMBRE_PAIS_ORIG,NOMBRE_VIA_TRANSPORTE,NOMBRE_PUERTO_EMBARQUE,NOMBRE_PUERTO_DESEMBARQUE,NOMBRE_TIPO_CARGA,NUM_MANIF,NOMBRE_NAVE,NOMBRE_AGENTE_DE_NAVES,NUM_CONOC,FEC_CONOC,NOMEMISOR,NOMBRE_MONEDA,FOB,FLETE,SEGURO,CIF,ARANC_NAC,CANT_MERC_SUM,NUMITEM_MAX
1357,20986046,103,SAN ANTONIO,SANTIAGO,5806,REINO UNIDO,"MARITIMA, FLUVIAL Y LACUSTRE",OTROS PTOS.INGLATERR,SAN ANTONIO,GENERAL,236030,NaN,NaN,HLCULIV230912683,16092023,HAPAG LLOYD,LIBRA EST,"60824,63","2294,21","1216,49","64335,33",87059000,18,18

In [35]:
df_example = df_example.rename(columns={
    "CANT_MERC_SUM": "TOTAL_BULTOS"
})

In [36]:
df_example = df_example.drop(columns=['NUMITEM_MAX'])

In [37]:
df_example.to_csv('informacion_base_importaciones_vehiculos.csv', index=False, encoding='utf-8')